server:
  port: 8080


providerServer: http://wdxmsc-provider-8081/depart/

spring:
  application:
    name: wdxmsc-client-8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
