server:
  port: 8888

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://aliyunOS:3306/springboot?useUnicode=true&charaterEncoding=utf8
    username: root
    password: wdx082018
  redis:
    host: aliyunOS
    port: 6379
  cache:
    type: redis
    cache-names: realTimeCache
  application:
    name: provider
  dubbo:
    registry: zookeeper://aliyunOS:2181

mybatis:
  mapper-locations: classpath*:xml/*.xml
  type-aliases-package: com.wdx.dubbo.model
